import '../domain/entities/price_quote.dart';

/// Static catalog of supported assets.
///
/// Only assets with a VERIFIED data source may be [enabled].
/// Iranian free-market, gold and coin quotes come from the public keyless
/// TGJU feed (see IranianMarketProvider) with the feed's own timestamps.
/// Anything without such a source stays disabled (DATA UNAVAILABLE).
class AssetDefinition {
  const AssetDefinition({
    required this.id,
    required this.symbol,
    required this.name,
    required this.nameFa,
    required this.category,
    required this.unit,
    required this.currency,
    this.enabled = true,
    this.tradable = true,
  });

  final String id;
  final String symbol;
  final String name;
  final String nameFa;
  final AssetCategory category;
  final String unit;
  final String currency;
  final bool enabled;

  /// False for observations you cannot hold: a market index or a coin
  /// bubble is a real published number, but it is not a position, so the
  /// portfolio and the converter leave it out.
  final bool tradable;
}

abstract final class AssetCatalog {
  // ---- GLOBAL CURRENCY (verified: open.er-api.com + jsDelivr + ECB) ----
  static const globalCurrencies = <AssetDefinition>[
    _usd,
    _eur,
    _gbp,
    _aed,
    _try_,
    _cny,
    _irr,
    _cad,
    _aud,
    _chf,
    _jpy,
    AssetDefinition(
      id: 'fx_pkr',
      symbol: 'PKR',
      name: 'Pakistani Rupee',
      nameFa: 'روپیه پاکستان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'PKR',
    ),
    AssetDefinition(
      id: 'fx_inr',
      symbol: 'INR',
      name: 'Indian Rupee',
      nameFa: 'روپیه هند',
      category: AssetCategory.currency,
      unit: '',
      currency: 'INR',
    ),
    AssetDefinition(
      id: 'fx_qar',
      symbol: 'QAR',
      name: 'Qatari Riyal',
      nameFa: 'ریال قطر',
      category: AssetCategory.currency,
      unit: '',
      currency: 'QAR',
    ),
    AssetDefinition(
      id: 'fx_kwd',
      symbol: 'KWD',
      name: 'Kuwaiti Dinar',
      nameFa: 'دینار کویت',
      category: AssetCategory.currency,
      unit: '',
      currency: 'KWD',
    ),
    AssetDefinition(
      id: 'fx_bhd',
      symbol: 'BHD',
      name: 'Bahraini Dinar',
      nameFa: 'دینار بحرین',
      category: AssetCategory.currency,
      unit: '',
      currency: 'BHD',
    ),
    AssetDefinition(
      id: 'fx_omr',
      symbol: 'OMR',
      name: 'Omani Rial',
      nameFa: 'ریال عمان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'OMR',
    ),
    AssetDefinition(
      id: 'fx_sar',
      symbol: 'SAR',
      name: 'Saudi Riyal',
      nameFa: 'ریال عربستان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'SAR',
    ),
    AssetDefinition(
      id: 'fx_jod',
      symbol: 'JOD',
      name: 'Jordanian Dinar',
      nameFa: 'دینار اردن',
      category: AssetCategory.currency,
      unit: '',
      currency: 'JOD',
    ),
    AssetDefinition(
      id: 'fx_syp',
      symbol: 'SYP',
      name: 'Syrian Pound',
      nameFa: 'لیر سوریه',
      category: AssetCategory.currency,
      unit: '',
      currency: 'SYP',
    ),
    AssetDefinition(
      id: 'fx_myr',
      symbol: 'MYR',
      name: 'Malaysian Ringgit',
      nameFa: 'رینگیت مالزی',
      category: AssetCategory.currency,
      unit: '',
      currency: 'MYR',
    ),
    AssetDefinition(
      id: 'fx_thb',
      symbol: 'THB',
      name: 'Thai Baht',
      nameFa: 'بات تایلند',
      category: AssetCategory.currency,
      unit: '',
      currency: 'THB',
    ),
    AssetDefinition(
      id: 'fx_sgd',
      symbol: 'SGD',
      name: 'Singapore Dollar',
      nameFa: 'دلار سنگاپور',
      category: AssetCategory.currency,
      unit: '',
      currency: 'SGD',
    ),
    AssetDefinition(
      id: 'fx_hkd',
      symbol: 'HKD',
      name: 'Hong Kong Dollar',
      nameFa: 'دلار هنگ‌کنگ',
      category: AssetCategory.currency,
      unit: '',
      currency: 'HKD',
    ),
    AssetDefinition(
      id: 'fx_krw',
      symbol: 'KRW',
      name: 'South Korean Won',
      nameFa: 'وون کره جنوبی',
      category: AssetCategory.currency,
      unit: '',
      currency: 'KRW',
    ),
    AssetDefinition(
      id: 'fx_nzd',
      symbol: 'NZD',
      name: 'New Zealand Dollar',
      nameFa: 'دلار نیوزیلند',
      category: AssetCategory.currency,
      unit: '',
      currency: 'NZD',
    ),
    AssetDefinition(
      id: 'fx_sek',
      symbol: 'SEK',
      name: 'Swedish Krona',
      nameFa: 'کرون سوئد',
      category: AssetCategory.currency,
      unit: '',
      currency: 'SEK',
    ),
    AssetDefinition(
      id: 'fx_nok',
      symbol: 'NOK',
      name: 'Norwegian Krone',
      nameFa: 'کرون نروژ',
      category: AssetCategory.currency,
      unit: '',
      currency: 'NOK',
    ),
    AssetDefinition(
      id: 'fx_dkk',
      symbol: 'DKK',
      name: 'Danish Krone',
      nameFa: 'کرون دانمارک',
      category: AssetCategory.currency,
      unit: '',
      currency: 'DKK',
    ),
    AssetDefinition(
      id: 'fx_pln',
      symbol: 'PLN',
      name: 'Polish Zloty',
      nameFa: 'زلوتی لهستان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'PLN',
    ),
    AssetDefinition(
      id: 'fx_ron',
      symbol: 'RON',
      name: 'Romanian Leu',
      nameFa: 'لئوی رومانی',
      category: AssetCategory.currency,
      unit: '',
      currency: 'RON',
    ),
    AssetDefinition(
      id: 'fx_azn',
      symbol: 'AZN',
      name: 'Azerbaijani Manat',
      nameFa: 'منات آذربایجان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'AZN',
    ),
    AssetDefinition(
      id: 'fx_amd',
      symbol: 'AMD',
      name: 'Armenian Dram',
      nameFa: 'درام ارمنستان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'AMD',
    ),
    AssetDefinition(
      id: 'fx_gel',
      symbol: 'GEL',
      name: 'Georgian Lari',
      nameFa: 'لاری گرجستان',
      category: AssetCategory.currency,
      unit: '',
      currency: 'GEL',
    ),
    AssetDefinition(
      id: 'fx_egp',
      symbol: 'EGP',
      name: 'Egyptian Pound',
      nameFa: 'پوند مصر',
      category: AssetCategory.currency,
      unit: '',
      currency: 'EGP',
    ),
    AssetDefinition(
      id: 'fx_bdt',
      symbol: 'BDT',
      name: 'Bangladeshi Taka',
      nameFa: 'تاکای بنگلادش',
      category: AssetCategory.currency,
      unit: '',
      currency: 'BDT',
    ),
    AssetDefinition(
      id: 'fx_lkr',
      symbol: 'LKR',
      name: 'Sri Lankan Rupee',
      nameFa: 'روپیه سریلانکا',
      category: AssetCategory.currency,
      unit: '',
      currency: 'LKR',
    ),
    AssetDefinition(
      id: 'fx_npr',
      symbol: 'NPR',
      name: 'Nepalese Rupee',
      nameFa: 'روپیه نپال',
      category: AssetCategory.currency,
      unit: '',
      currency: 'NPR',
    ),
  ];

  // ---- IRANIAN FREE MARKET (verified keyless: TGJU live feed) ----
  static const iranianMarket = <AssetDefinition>[
    AssetDefinition(
      id: 'ir_usd',
      symbol: 'USD/IRR-FM',
      name: 'US Dollar (Free Market)',
      nameFa: 'دلار آمریکا (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_eur',
      symbol: 'EUR/IRR-FM',
      name: 'Euro (Free Market)',
      nameFa: 'یورو (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_aed',
      symbol: 'AED/IRR-FM',
      name: 'UAE Dirham (Free Market)',
      nameFa: 'درهم امارات (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_gbp',
      symbol: 'GBP/IRR-FM',
      name: 'British Pound (Free Market)',
      nameFa: 'پوند انگلیس (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_try',
      symbol: 'TRY/IRR-FM',
      name: 'Turkish Lira (Free Market)',
      nameFa: 'لیر ترکیه (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_cny',
      symbol: 'CNY/IRR-FM',
      name: 'Chinese Yuan (Free Market)',
      nameFa: 'یوان چین (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_cad',
      symbol: 'CAD/IRR-FM',
      name: 'Canadian Dollar (Free Market)',
      nameFa: 'دلار کانادا (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_aud',
      symbol: 'AUD/IRR-FM',
      name: 'Australian Dollar (Free Market)',
      nameFa: 'دلار استرالیا (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_chf',
      symbol: 'CHF/IRR-FM',
      name: 'Swiss Franc (Free Market)',
      nameFa: 'فرانک سوئیس (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    // TGJU publishes the yen per 100 units — the name says so, because the
    // number on screen is the price of 100 yen, not one.
    AssetDefinition(
      id: 'ir_jpy',
      symbol: 'JPY100/IRR-FM',
      name: 'Japanese Yen per 100 (Free Market)',
      nameFa: 'ین ژاپن، هر ۱۰۰ ین (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_rub',
      symbol: 'RUB/IRR-FM',
      name: 'Russian Ruble (Free Market)',
      nameFa: 'روبل روسیه (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_iqd',
      symbol: 'IQD/IRR-FM',
      name: 'Iraqi Dinar (Free Market)',
      nameFa: 'دینار عراق (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    // Trades around the clock, unlike every other Iranian-market row. At
    // night this is the only live Toman price the market offers, and it is
    // what the free-market dollar is read from once the bazaar closes.
    AssetDefinition(
      id: 'usdt_irt',
      symbol: 'USDT/IRT',
      name: 'Tether in Toman',
      nameFa: 'تتر (تومان) — ۲۴ ساعته',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_pkr',
      symbol: 'PKR/IRR-FM',
      name: 'Pakistani Rupee (Free Market)',
      nameFa: 'روپیه پاکستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_inr',
      symbol: 'INR/IRR-FM',
      name: 'Indian Rupee (Free Market)',
      nameFa: 'روپیه هند (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_qar',
      symbol: 'QAR/IRR-FM',
      name: 'Qatari Riyal (Free Market)',
      nameFa: 'ریال قطر (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_kwd',
      symbol: 'KWD/IRR-FM',
      name: 'Kuwaiti Dinar (Free Market)',
      nameFa: 'دینار کویت (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_bhd',
      symbol: 'BHD/IRR-FM',
      name: 'Bahraini Dinar (Free Market)',
      nameFa: 'دینار بحرین (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_omr',
      symbol: 'OMR/IRR-FM',
      name: 'Omani Rial (Free Market)',
      nameFa: 'ریال عمان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_sar',
      symbol: 'SAR/IRR-FM',
      name: 'Saudi Riyal (Free Market)',
      nameFa: 'ریال عربستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_jod',
      symbol: 'JOD/IRR-FM',
      name: 'Jordanian Dinar (Free Market)',
      nameFa: 'دینار اردن (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_syp',
      symbol: 'SYP/IRR-FM',
      name: 'Syrian Pound (Free Market)',
      nameFa: 'لیر سوریه (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_myr',
      symbol: 'MYR/IRR-FM',
      name: 'Malaysian Ringgit (Free Market)',
      nameFa: 'رینگیت مالزی (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_thb',
      symbol: 'THB/IRR-FM',
      name: 'Thai Baht (Free Market)',
      nameFa: 'بات تایلند (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_sgd',
      symbol: 'SGD/IRR-FM',
      name: 'Singapore Dollar (Free Market)',
      nameFa: 'دلار سنگاپور (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_hkd',
      symbol: 'HKD/IRR-FM',
      name: 'Hong Kong Dollar (Free Market)',
      nameFa: 'دلار هنگ‌کنگ (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_krw',
      symbol: 'KRW/IRR-FM',
      name: 'South Korean Won (Free Market)',
      nameFa: 'وون کره جنوبی (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_nzd',
      symbol: 'NZD/IRR-FM',
      name: 'New Zealand Dollar (Free Market)',
      nameFa: 'دلار نیوزیلند (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_sek',
      symbol: 'SEK/IRR-FM',
      name: 'Swedish Krona (Free Market)',
      nameFa: 'کرون سوئد (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_nok',
      symbol: 'NOK/IRR-FM',
      name: 'Norwegian Krone (Free Market)',
      nameFa: 'کرون نروژ (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_dkk',
      symbol: 'DKK/IRR-FM',
      name: 'Danish Krone (Free Market)',
      nameFa: 'کرون دانمارک (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_pln',
      symbol: 'PLN/IRR-FM',
      name: 'Polish Zloty (Free Market)',
      nameFa: 'زلوتی لهستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_ron',
      symbol: 'RON/IRR-FM',
      name: 'Romanian Leu (Free Market)',
      nameFa: 'لئوی رومانی (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_azn',
      symbol: 'AZN/IRR-FM',
      name: 'Azerbaijani Manat (Free Market)',
      nameFa: 'منات آذربایجان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_amd',
      symbol: 'AMD/IRR-FM',
      name: 'Armenian Dram (Free Market)',
      nameFa: 'درام ارمنستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_gel',
      symbol: 'GEL/IRR-FM',
      name: 'Georgian Lari (Free Market)',
      nameFa: 'لاری گرجستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_egp',
      symbol: 'EGP/IRR-FM',
      name: 'Egyptian Pound (Free Market)',
      nameFa: 'پوند مصر (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_bdt',
      symbol: 'BDT/IRR-FM',
      name: 'Bangladeshi Taka (Free Market)',
      nameFa: 'تاکای بنگلادش (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_lkr',
      symbol: 'LKR/IRR-FM',
      name: 'Sri Lankan Rupee (Free Market)',
      nameFa: 'روپیه سریلانکا (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_npr',
      symbol: 'NPR/IRR-FM',
      name: 'Nepalese Rupee (Free Market)',
      nameFa: 'روپیه نپال (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'ir_afn',
      symbol: 'AFN/IRR-FM',
      name: 'Afghan Afghani (Free Market)',
      nameFa: 'افغانی افغانستان (بازار آزاد)',
      category: AssetCategory.iranianCurrency,
      unit: 'تومان',
      currency: 'IRR',
    ),
  ];

  // ---- GOLD & COINS (verified keyless: TGJU live feed) ----
  static const goldAndCoins = <AssetDefinition>[
    AssetDefinition(
      id: 'gold_18k',
      symbol: 'GOLD-18K',
      name: 'Gold 18K',
      nameFa: 'طلای ۱۸ عیار',
      category: AssetCategory.gold,
      unit: 'گرم',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'gold_24k',
      symbol: 'GOLD-24K',
      name: 'Gold 24K',
      nameFa: 'طلای ۲۴ عیار',
      category: AssetCategory.gold,
      unit: 'گرم',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'mesghal',
      symbol: 'MESGHAL',
      name: 'Mesghal Gold',
      nameFa: 'مثقال طلا',
      category: AssetCategory.gold,
      unit: 'مثقال',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'xau_usd',
      symbol: 'XAU/USD',
      name: 'Gold Ounce / USD',
      nameFa: 'انس جهانی طلا',
      category: AssetCategory.gold,
      unit: 'اونس',
      currency: 'USD',
    ),
    AssetDefinition(
      id: 'silver',
      symbol: 'XAG/USD',
      name: 'Silver Ounce / USD',
      nameFa: 'انس جهانی نقره',
      category: AssetCategory.gold,
      unit: 'اونس',
      currency: 'USD',
    ),
    AssetDefinition(
      id: 'gold_abshodeh',
      symbol: 'ABSHODEH',
      name: 'Melted Gold (spot)',
      nameFa: 'آبشده نقدی',
      category: AssetCategory.gold,
      unit: 'مثقال',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'gold_abshodeh_mini',
      symbol: 'ABSHODEH-MINI',
      name: 'Melted Gold (mini size)',
      nameFa: 'آبشده مینی‌سایز',
      category: AssetCategory.gold,
      unit: 'گرم',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_emami',
      symbol: 'COIN-EMAMI',
      name: 'Emami Coin',
      nameFa: 'سکه امامی',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_bahar',
      symbol: 'COIN-BAHAR',
      name: 'Bahare Azadi Coin',
      nameFa: 'سکه بهاره آزادی',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_half',
      symbol: 'COIN-HALF',
      name: 'Half Coin',
      nameFa: 'نیم سکه',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_quarter',
      symbol: 'COIN-QUARTER',
      name: 'Quarter Coin',
      nameFa: 'ربع سکه',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_gram',
      symbol: 'COIN-GRAM',
      name: 'Gram Gold Coin',
      nameFa: 'سکه گرمی',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    AssetDefinition(
      id: 'coin_emami_retail',
      symbol: 'COIN-EMAMI-RETAIL',
      name: 'Emami Coin (retail)',
      nameFa: 'سکه امامی (خرده‌فروشی)',
      category: AssetCategory.coin,
      unit: 'عدد',
      currency: 'IRR',
    ),
    // «حباب» is published by TGJU itself — the premium over intrinsic gold
    // value. Real quoted data, not something this app computes. Not a
    // position you can hold, so it stays out of the portfolio/converter.
    AssetDefinition(
      id: 'coin_bahar_bubble',
      symbol: 'COIN-BAHAR-BUBBLE',
      name: 'Bahare Azadi Coin bubble',
      nameFa: 'حباب سکه بهار آزادی',
      category: AssetCategory.coin,
      unit: 'تومان',
      currency: 'IRR',
      tradable: false,
    ),
    AssetDefinition(
      id: 'coin_gram_bubble',
      symbol: 'COIN-GRAM-BUBBLE',
      name: 'Gram Coin bubble',
      nameFa: 'حباب سکه گرمی',
      category: AssetCategory.coin,
      unit: 'تومان',
      currency: 'IRR',
      tradable: false,
    ),
    AssetDefinition(
      id: 'coin_half_bubble',
      symbol: 'COIN-HALF-BUBBLE',
      name: 'Half Coin bubble',
      nameFa: 'حباب نیم سکه',
      category: AssetCategory.coin,
      unit: 'تومان',
      currency: 'IRR',
      tradable: false,
    ),
    AssetDefinition(
      id: 'coin_quarter_bubble',
      symbol: 'COIN-QUARTER-BUBBLE',
      name: 'Quarter Coin bubble',
      nameFa: 'حباب ربع سکه',
      category: AssetCategory.coin,
      unit: 'تومان',
      currency: 'IRR',
      tradable: false,
    ),
  ];

  // ---- CRYPTO (verified: CoinGecko public API) ----
  static const crypto = <AssetDefinition>[
    AssetDefinition(
      id: 'btc_usd',
      symbol: 'BTC/USD',
      name: 'Bitcoin',
      nameFa: 'بیت‌کوین',
      category: AssetCategory.crypto,
      unit: '',
      currency: 'USD',
    ),
    AssetDefinition(
      id: 'eth_usd',
      symbol: 'ETH/USD',
      name: 'Ethereum',
      nameFa: 'اتریوم',
      category: AssetCategory.crypto,
      unit: '',
      currency: 'USD',
    ),
    AssetDefinition(
      id: 'usdt_usd',
      symbol: 'USDT/USD',
      name: 'Tether',
      nameFa: 'تتر',
      category: AssetCategory.crypto,
      unit: '',
      currency: 'USD',
    ),
  ];

  // ---- INDEX (verified keyless: TGJU live feed) ----
  // Index points, NOT Rial: currency 'IDX' keeps it out of every
  // Rial->Toman conversion path.
  static const indices = <AssetDefinition>[
    AssetDefinition(
      id: 'bourse_index',
      symbol: 'TEDPIX',
      name: 'Tehran Stock Exchange index',
      nameFa: 'شاخص کل بورس',
      category: AssetCategory.marketIndex,
      unit: 'واحد',
      currency: 'IDX',
      tradable: false,
    ),
  ];

  // ---- COMMODITY (verified keyless: TGJU live feed, USD per barrel) ----
  static const commodities = <AssetDefinition>[
    AssetDefinition(
      id: 'oil_brent',
      symbol: 'BRENT',
      name: 'Brent crude',
      nameFa: 'نفت برنت',
      category: AssetCategory.commodity,
      unit: 'بشکه',
      currency: 'USD',
    ),
    AssetDefinition(
      id: 'oil_wti',
      symbol: 'WTI',
      name: 'WTI crude',
      nameFa: 'نفت وست تگزاس',
      category: AssetCategory.commodity,
      unit: 'بشکه',
      currency: 'USD',
    ),
  ];

  static const all = <AssetDefinition>[
    ...globalCurrencies,
    ...iranianMarket,
    ...goldAndCoins,
    ...crypto,
    ...indices,
    ...commodities,
  ];

  static AssetDefinition? byId(String id) {
    for (final a in all) {
      if (a.id == id) return a;
    }
    return null;
  }

  static const _usd = AssetDefinition(
    id: 'fx_usd',
    symbol: 'USD',
    name: 'US Dollar',
    nameFa: 'دلار آمریکا',
    category: AssetCategory.currency,
    unit: '',
    currency: 'USD',
  );
  static const _eur = AssetDefinition(
    id: 'fx_eur',
    symbol: 'EUR',
    name: 'Euro',
    nameFa: 'یورو',
    category: AssetCategory.currency,
    unit: '',
    currency: 'EUR',
  );
  static const _gbp = AssetDefinition(
    id: 'fx_gbp',
    symbol: 'GBP',
    name: 'British Pound',
    nameFa: 'پوند انگلیس',
    category: AssetCategory.currency,
    unit: '',
    currency: 'GBP',
  );
  static const _aed = AssetDefinition(
    id: 'fx_aed',
    symbol: 'AED',
    name: 'UAE Dirham',
    nameFa: 'درهم امارات',
    category: AssetCategory.currency,
    unit: '',
    currency: 'AED',
  );
  static const _try_ = AssetDefinition(
    id: 'fx_try',
    symbol: 'TRY',
    name: 'Turkish Lira',
    nameFa: 'لیر ترکیه',
    category: AssetCategory.currency,
    unit: '',
    currency: 'TRY',
  );
  static const _cny = AssetDefinition(
    id: 'fx_cny',
    symbol: 'CNY',
    name: 'Chinese Yuan',
    nameFa: 'یوان چین',
    category: AssetCategory.currency,
    unit: '',
    currency: 'CNY',
  );
  static const _cad = AssetDefinition(
    id: 'fx_cad',
    symbol: 'CAD',
    name: 'Canadian Dollar',
    nameFa: 'دلار کانادا',
    category: AssetCategory.currency,
    unit: '',
    currency: 'CAD',
  );
  static const _aud = AssetDefinition(
    id: 'fx_aud',
    symbol: 'AUD',
    name: 'Australian Dollar',
    nameFa: 'دلار استرالیا',
    category: AssetCategory.currency,
    unit: '',
    currency: 'AUD',
  );
  static const _chf = AssetDefinition(
    id: 'fx_chf',
    symbol: 'CHF',
    name: 'Swiss Franc',
    nameFa: 'فرانک سوئیس',
    category: AssetCategory.currency,
    unit: '',
    currency: 'CHF',
  );
  static const _jpy = AssetDefinition(
    id: 'fx_jpy',
    symbol: 'JPY',
    name: 'Japanese Yen',
    nameFa: 'ین ژاپن',
    category: AssetCategory.currency,
    unit: '',
    currency: 'JPY',
  );

  /// Official published IRR rate (real source data; NOT free-market).
  static const _irr = AssetDefinition(
    id: 'fx_irr',
    symbol: 'USD/IRR',
    name: 'Iranian Rial (official)',
    nameFa: 'ریال ایران (رسمی)',
    category: AssetCategory.currency,
    unit: 'ریال',
    currency: 'IRR',
  );
}
